version: '3'

services:
  redis:
    container_name: redis
    image: 'bitnami/redis:latest'
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=password123
    volumes:
    - ./data:/bitnami/redis/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
